# Generated by Django 6.0.6 on 2026-06-06 20:11

import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("text", 0), ("image", 1), ("embed", 2), ("code", 5)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "e.g. python, javascript, bash", "required": False},
                            ),
                            4: ("wagtail.blocks.TextBlock", (), {}),
                            5: ("wagtail.blocks.StructBlock", [[("language", 3), ("code", 4)]], {}),
                        },
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge article",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="KnowledgeIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Knowledge index page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="DraftSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "submission_type",
                    models.CharField(
                        choices=[("news", "News"), ("knowledge_article", "Knowledge article")], max_length=30
                    ),
                ),
                ("locale", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100)),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewer_note", models.TextField(blank=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Draft submission",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="LocationArticlePage",
            fields=[
                (
                    "knowledgearticlepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="knowledge.knowledgearticlepage",
                    ),
                ),
                ("gpx_file", models.FileField(blank=True, upload_to="knowledge/gpx/")),
                (
                    "photo_gallery",
                    wagtail.fields.StreamField(
                        [("image", 0)],
                        blank=True,
                        block_lookup={0: ("wagtail.images.blocks.ImageChooserBlock", (), {})},
                    ),
                ),
                (
                    "external_links",
                    wagtail.fields.StreamField(
                        [("link", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.URLBlock", (), {}),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("komoot", "Komoot"),
                                        ("strava", "Strava"),
                                        ("ridewithgps", "RideWithGPS"),
                                        ("other", "Other"),
                                    ],
                                    "required": False,
                                },
                            ),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("url", 1), ("platform", 2)]], {}),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Location article",
            },
            bases=("knowledge.knowledgearticlepage",),
        ),
        migrations.CreateModel(
            name="KnowledgeArticlePageTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="knowledge.knowledgearticlepage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="knowledgearticlepage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="knowledge.KnowledgeArticlePageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
