# Generated by Django 6.0.6 on 2026-06-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftsubmission",
            name="locale",
            field=models.CharField(choices=[("ru", "Russian"), ("kk", "Kazakh"), ("en", "English")], max_length=10),
        ),
    ]
