# Generated by Django 6.0.6 on 2026-06-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0002_alter_draftsubmission_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgearticlepage",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
