# Generated by Django 6.0.6 on 2026-06-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0003_add_is_hidden_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgearticlepage",
            name="is_hidden",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
