# Generated by Django 6.0.6 on 2026-06-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0005_create_knowledge_index_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftsubmission",
            name="body",
            field=models.TextField(verbose_name="Body"),
        ),
        migrations.AlterField(
            model_name="draftsubmission",
            name="category",
            field=models.CharField(blank=True, max_length=100, verbose_name="Category"),
        ),
        migrations.AlterField(
            model_name="draftsubmission",
            name="locale",
            field=models.CharField(
                choices=[("ru", "Russian"), ("kk", "Kazakh"), ("en", "English")], max_length=10, verbose_name="Locale"
            ),
        ),
        migrations.AlterField(
            model_name="draftsubmission",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
    ]
