# Generated by Django 6.0.6 on 2026-06-20 09:01

import django.db.models.deletion
import django.utils.timezone
import modelsearch.index
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0006_alter_draftsubmission_verbose_names"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Russian"), ("kk", "Kazakh"), ("en", "English")],
                        db_index=True,
                        default="ru",
                        max_length=10,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_hidden", models.BooleanField(db_index=True, default=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge article",
                "verbose_name_plural": "Knowledge articles",
                "ordering": ["-published_at"],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
