# Generated by Django 6.0.6 on 2026-06-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0010_remove_knowledgearticlepage_page_ptr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgearticle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
