# Generated by Django 6.0.6 on 2026-06-09 03:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                ("title_kk", models.CharField(max_length=255, null=True)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("intro", models.CharField(blank=True, max_length=500)),
                ("intro_ru", models.CharField(blank=True, max_length=500, null=True)),
                ("intro_kk", models.CharField(blank=True, max_length=500, null=True)),
                ("intro_en", models.CharField(blank=True, max_length=500, null=True)),
                ("body", models.TextField(blank=True)),
                ("body_ru", models.TextField(blank=True, null=True)),
                ("body_kk", models.TextField(blank=True, null=True)),
                ("body_en", models.TextField(blank=True, null=True)),
                ("hero_image", models.ImageField(blank=True, null=True, upload_to="news/hero/")),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "News article",
                "verbose_name_plural": "News articles",
                "ordering": ["-published_at"],
            },
        ),
    ]
