# Generated by Django 6.0.6 on 2026-06-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_newsarticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="is_hidden",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
