# Generated by Django 6.0.6 on 2026-06-21 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0013_descriptions_to_html"),
        ("protocols", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StartListUpload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_id", models.CharField(max_length=64)),
                ("items", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_list_uploads",
                        to="calendar_app.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["device_id"],
                "unique_together": {("competition", "device_id")},
            },
        ),
    ]
