# Generated by Django 6.0.6 on 2026-06-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocols", "0002_startlistupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="startlistupload",
            name="client_revision",
            field=models.BigIntegerField(default=0),
        ),
    ]
