# Generated by Django 6.0.6 on 2026-06-30 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0016_qualify_other_and_add_mtb_disciplines"),
        ("protocols", "0003_startlistupload_client_revision"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinishTimesUpload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_id", models.CharField(max_length=64)),
                ("items", models.JSONField(default=list)),
                ("client_revision", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finish_times_uploads",
                        to="calendar_app.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["device_id"],
                "abstract": False,
                "unique_together": {("competition", "device_id")},
            },
        ),
        migrations.CreateModel(
            name="GroupTimesUpload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_id", models.CharField(max_length=64)),
                ("items", models.JSONField(default=list)),
                ("client_revision", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_times_uploads",
                        to="calendar_app.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["device_id"],
                "abstract": False,
                "unique_together": {("competition", "device_id")},
            },
        ),
        migrations.CreateModel(
            name="RemotePointUpload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_id", models.CharField(max_length=64)),
                ("items", models.JSONField(default=list)),
                ("client_revision", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("point_number", models.PositiveIntegerField()),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_point_uploads",
                        to="calendar_app.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["point_number", "device_id"],
                "abstract": False,
                "unique_together": {("competition", "device_id", "point_number")},
            },
        ),
    ]
