# Generated by Django 6.0.6 on 2026-07-08 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0019_alter_competition_upload_token"),
        ("protocols", "0004_finishtimesupload_grouptimesupload_remotepointupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionLiveStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_stats",
                        to="calendar_app.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition live stats",
                "verbose_name_plural": "Competition live stats",
            },
        ),
    ]
