# Generated by Django 6.0.6 on 2026-06-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(choices=[("light", "Light"), ("dark", "Dark")], default="light", max_length=10),
        ),
    ]
