# Generated by Django 6.0.6 on 2026-06-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_gender_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
