# Generated by Django 6.0.6 on 2026-06-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_preferred_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[("", "Auto"), ("ru", "Russian"), ("kk", "Kazakh"), ("en", "English")],
                default="",
                max_length=10,
            ),
        ),
    ]
