# Generated by Django 6.0.6 on 2026-06-09 13:54

from django.db import migrations

_RENAMES = [
    ("participants", "Participants"),
    ("organizers", "Organizers"),
    ("admins", "Admins"),
    ("owners", "Owners"),
]


def rename_groups_to_titlecase(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for old_name, new_name in _RENAMES:
        Group.objects.filter(name=old_name).update(name=new_name)


def rename_groups_to_lowercase(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for old_name, new_name in _RENAMES:
        Group.objects.filter(name=new_name).update(name=old_name)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_preferred_language_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(rename_groups_to_titlecase, rename_groups_to_lowercase),
    ]
