# Generated by Django 6.0.6 on 2026-06-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_fix_wagtailuserprofile_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_token",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
