# Generated by Django 6.0.6 on 2026-06-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_add_api_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_confirmation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
