# Generated by Django 6.0.6 on 2026-06-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_drop_legacy_auth_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
