# Generated by Django 6.0.7 on 2026-07-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_user_city_user_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="strava_link",
            field=models.URLField(blank=True, default=""),
        ),
    ]
