# Generated by Django 6.0.7 on 2026-07-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_user_strava_link"),
        ("calendar_app", "0024_competition_additional_info_required"),
        ("locations", "0016_country_centroids"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_directions",
            field=models.ManyToManyField(
                blank=True, related_name="preferring_users", to="calendar_app.disciplinecategory"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_disciplines",
            field=models.ManyToManyField(blank=True, related_name="preferring_users", to="calendar_app.discipline"),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_locations",
            field=models.ManyToManyField(blank=True, related_name="preferring_users", to="locations.location"),
        ),
    ]
