# Generated by Django 6.0.6 on 2026-06-07 04:52

import django.db.models.deletion
import modelsearch.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CyclingDiscipline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("name_ru", models.CharField(max_length=100, null=True)),
                ("name_kk", models.CharField(max_length=100, null=True)),
                ("name_en", models.CharField(max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Cycling discipline",
                "verbose_name_plural": "Cycling disciplines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("name_ru", models.CharField(max_length=100, null=True)),
                ("name_kk", models.CharField(max_length=100, null=True)),
                ("name_en", models.CharField(max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Event type",
                "verbose_name_plural": "Event types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                ("title_kk", models.CharField(max_length=255, null=True)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
                ("description_kk", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending_approval",
                        max_length=30,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("url_route", models.URLField(blank=True)),
                ("url_announcement", models.URLField(blank=True)),
                ("url_registration", models.URLField(blank=True)),
                ("url_regulations", models.URLField(blank=True)),
                ("url_results", models.URLField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competitions",
                        to="locations.location",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="calendar_app.cyclingdiscipline",
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="calendar_app.eventtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition",
                "verbose_name_plural": "Competitions",
                "ordering": ["date_start"],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
