# Generated by Django 6.0.6 on 2026-06-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0003_competition_registration_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="file_announcement",
            field=models.FileField(blank=True, upload_to="competitions/announcements/"),
        ),
        migrations.AddField(
            model_name="competition",
            name="file_regulations",
            field=models.FileField(blank=True, upload_to="competitions/regulations/"),
        ),
        migrations.AddField(
            model_name="competition",
            name="file_results",
            field=models.FileField(blank=True, upload_to="competitions/results/"),
        ),
        migrations.AddField(
            model_name="competition",
            name="file_route",
            field=models.FileField(blank=True, upload_to="competitions/routes/"),
        ),
    ]
