# Generated by Django 6.0.6 on 2026-06-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0005_competitioncomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitioncomment",
            name="body",
            field=models.TextField(max_length=2000),
        ),
    ]
