# Generated by Django 6.0.6 on 2026-06-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0006_comment_body_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitioncomment",
            name="body",
            field=models.CharField(max_length=2000),
        ),
    ]
