# Generated by Django 6.0.6 on 2026-07-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0016_qualify_other_and_add_mtb_disciplines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="registration_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
