# Generated by Django 6.0.6 on 2026-07-04 15:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0018_shift_date_deadlines_to_end_of_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="upload_token",
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
