# Generated by Django 6.0.7 on 2026-07-15 12:48

from django.db import migrations, models


def _forward(apps, schema_editor):
    """Carry the old boolean into the new mode: unchecked -> none, checked -> free.

    The new column defaults to ``free``, so only the unchecked rows need updating. Done with
    a single ``update`` so the line runs (and is covered) even against an empty test database.
    """
    Competition = apps.get_model("calendar_app", "Competition")
    Competition.objects.filter(show_additional_info_field=False).update(additional_info_mode="none")


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0021_competitionrejection"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="additional_info_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Do not show"),
                    ("free", "Free-form input"),
                    ("strava", "Strava link"),
                ],
                default="free",
                max_length=10,
            ),
        ),
        migrations.RunPython(_forward, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="competition",
            name="show_additional_info_field",
        ),
    ]
