# Generated by Django 6.0.7 on 2026-07-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0022_remove_competition_show_additional_info_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="show_additional_info_in_list",
            field=models.BooleanField(default=True),
        ),
    ]
