# Generated by Django 6.0.8 on 2026-09-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0030_competitionmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="additional_info_label",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
