# Generated by Django 6.0.8 on 2026-10-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0031_additional_info_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="preview_image",
            field=models.ImageField(blank=True, upload_to="competitions/preview/"),
        ),
    ]
