# Generated by Django 6.0.6 on 2026-06-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_aboutpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("navbar_title", models.CharField(blank=True, max_length=100, verbose_name="Navbar title")),
                (
                    "navbar_title_ru",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Navbar title"),
                ),
                (
                    "navbar_title_kk",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Navbar title"),
                ),
                (
                    "navbar_title_en",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Navbar title"),
                ),
                ("page_title", models.CharField(blank=True, max_length=200, verbose_name="Page title")),
                ("page_title_ru", models.CharField(blank=True, max_length=200, null=True, verbose_name="Page title")),
                ("page_title_kk", models.CharField(blank=True, max_length=200, null=True, verbose_name="Page title")),
                ("page_title_en", models.CharField(blank=True, max_length=200, null=True, verbose_name="Page title")),
                ("body", models.TextField(blank=True, verbose_name="Body")),
                ("body_ru", models.TextField(blank=True, null=True, verbose_name="Body")),
                ("body_kk", models.TextField(blank=True, null=True, verbose_name="Body")),
                ("body_en", models.TextField(blank=True, null=True, verbose_name="Body")),
            ],
            options={
                "verbose_name": "Site content",
            },
        ),
    ]
