# Generated by Django 6.0.6 on 2026-06-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0002_relay_participant_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionregistration",
            name="participant_birth_years",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="competitionregistration",
            name="participant_cities",
            field=models.TextField(blank=True, default=""),
        ),
    ]
