from typing import ClassVar

from django.conf import settings
from django.db import models
from django.utils import translation
from django.utils.translation import gettext
from treebeard.mp_tree import MP_Node
from wagtail.admin.panels import FieldPanel
from wagtail.fields import RichTextField
from wagtail.models import Page
from wagtail.search import index
from wagtail_localize.fields import SynchronizedField

from cycling_site.page_mixins import AsciiSlugMixin


def add_location_child(parent, **kwargs):
    """Append a child under ``parent`` at the next free path, sidestepping treebeard's
    sorted ``add_child``.

    A sorted MP tree assumes a sibling's path order matches its sort order, so inserting
    shifts later siblings' paths. Renaming a location changes its ``name`` sort key without
    re-pathing, which breaks that invariant and makes the next sorted insert collide on the
    unique ``path`` constraint -- a 500 when proposing/creating a venue. Appending at the
    real last path never shifts an existing node, and recomputing ``numchild`` heals a
    counter that has drifted (e.g. ``is_leaf`` wrongly reporting a populated node as empty).
    """
    cls = parent.__class__
    children = list(
        cls.objects.filter(
            depth=parent.depth + 1,
            path__range=cls._get_children_path_interval(parent.path),
        ).order_by("path")
    )
    last = children[-1] if children else None
    newpath = last._inc_path() if last is not None else cls._get_path(parent.path, parent.depth + 1, 1)
    obj = cls(path=newpath, depth=parent.depth + 1, numchild=0, **kwargs)
    obj.save()
    new_count = len(children) + 1
    if parent.numchild != new_count:
        cls.objects.filter(pk=parent.pk).update(numchild=new_count)
        parent.numchild = new_count
    return obj


class Location(MP_Node, index.Indexed):
    name = models.CharField(max_length=255)
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    lng = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)

    is_hidden = models.BooleanField(default=False, db_index=True)
    is_deleted = models.BooleanField(default=False, db_index=True)
    sort_order = models.PositiveSmallIntegerField(default=0, db_index=True)

    node_order_by: ClassVar[list] = ["sort_order", "name"]

    # name_ru / name_kk / name_en are generated by modeltranslation
    search_fields: ClassVar[list] = [
        index.SearchField("name_ru"),
        index.SearchField("name_kk"),
        index.SearchField("name_en"),
        index.FilterField("is_deleted"),
        index.FilterField("is_hidden"),
    ]

    panels: ClassVar[list] = [
        FieldPanel("name"),
        FieldPanel("lat"),
        FieldPanel("lng"),
    ]

    def __str__(self) -> str:
        return self.name or f"Location #{self.pk}"

    @staticmethod
    def _localized_names(source: str) -> dict:
        """Return {ru, kk, en} translations of a gettext source string."""
        names = {}
        for lang in ("ru", "kk", "en"):
            with translation.override(lang):
                names[lang] = gettext(source)
        return names

    @property
    def is_pending(self) -> bool:
        """True while the location has an unresolved proposal (issue #111)."""
        proposal = getattr(self, "proposal", None)
        return proposal is not None and proposal.status == LocationProposal.Status.PENDING_APPROVAL

    @classmethod
    def propose_venue(cls, city, name, lat=None, lng=None, *, submitted_by=None, approved=False) -> "Location":
        """Create a depth-4 venue under ``city``; pending (with a proposal) unless ``approved``."""
        venue = add_location_child(
            city, name=name, name_ru=name, name_kk=name, name_en=name, lat=lat, lng=lng, is_hidden=False
        )
        if not approved:
            LocationProposal.objects.create(location=venue, submitted_by=submitted_by)
        return venue

    @classmethod
    def get_or_create_other_location(cls, city) -> "Location":
        """The city's hidden "other location" fallback venue, created if missing."""
        # Query children by path (not get_children(), which returns nothing when a drifted
        # numchild makes the city look like a leaf) so we never create a duplicate fallback.
        existing = (
            cls.objects.filter(
                depth=city.depth + 1,
                path__range=cls._get_children_path_interval(city.path),
                is_hidden=True,
                is_deleted=False,
            )
            .order_by("path")
            .first()
        )
        if existing:
            return existing
        names = cls._localized_names("Other location")
        return add_location_child(
            city,
            name=names["ru"],
            name_ru=names["ru"],
            name_kk=names["kk"],
            name_en=names["en"],
            is_hidden=True,
        )

    def approve_with_competition(self) -> None:
        """Auto-approve a pending location when its competition is approved."""
        proposal = getattr(self, "proposal", None)
        if proposal is not None and proposal.status != LocationProposal.Status.APPROVED:
            proposal.status = LocationProposal.Status.APPROVED
            proposal.save(update_fields=["status"])

    def reject_and_reset_competitions(self) -> None:
        """Reject a proposed location: move its competitions to the city's other-location, then soft-delete it."""
        parent = self.get_parent()
        fallback = self.get_or_create_other_location(parent) if parent is not None else None
        self.competitions.update(location=fallback)
        self.is_deleted = True
        self.save(update_fields=["is_deleted"])

    class Meta:
        verbose_name = "Location"
        verbose_name_plural = "Locations"


class LocationProposal(models.Model):
    """A user-proposed location awaiting moderation (issue #111).

    Locations seeded or created by organizer+ have no proposal and are public at once.
    A pending proposal makes the location visible only to its proposer until approved;
    approving the competition that uses it (or a moderator) approves the proposal.
    """

    class Status(models.TextChoices):
        PENDING_APPROVAL = "pending_approval", "Pending approval"
        APPROVED = "approved", "Approved"

    location = models.OneToOneField(Location, on_delete=models.CASCADE, related_name="proposal")
    submitted_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING_APPROVAL,
        db_index=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"Proposal #{self.pk} for location {self.location_id} ({self.status})"


def competition_location_block_reason(location, user, *, is_admin=False) -> str | None:
    """Why ``user`` may not attach a competition to ``location`` (review #3), else None.

    Shared by the web submit/edit form and the competition API so a forged request can't
    use a deleted location or another user's pending (unmoderated) proposal.
    """
    if location is None:
        return None
    if getattr(location, "is_deleted", False):
        return "Location is deleted"
    # A competition must point at a specific venue (depth 4), never a country/region/city.
    if location.depth != 4:
        return "Competition location must be a specific venue, not a country/region/city"
    proposal = getattr(location, "proposal", None)
    if proposal is not None and proposal.status == LocationProposal.Status.PENDING_APPROVAL and not is_admin:
        owner_id = proposal.submitted_by_id
        if not (getattr(user, "is_authenticated", False) and owner_id == getattr(user, "pk", None)):
            return "Location proposal belongs to another user"
    return None


def nearest_visible_ancestor_with_coords(loc, by_path, step):
    """The nearest ancestor of ``loc`` (city -> region -> country) that is NOT hidden and
    has coordinates, looked up in ``by_path`` (path -> Location). Hidden ancestors are
    skipped so a hidden node never becomes a marker; None if none qualifies. ``by_path``
    is expected to exclude deleted nodes, so deleted ancestors are skipped too."""
    path = loc.path[:-step]
    while path:
        anc = by_path.get(path)
        if anc is not None and not anc.is_hidden and anc.lat is not None and anc.lng is not None:
            return anc
        path = path[:-step]
    return None


def map_display_node(loc, by_path, step):
    """The node ``loc`` should be drawn as on a map: itself when it is a visible node with
    coordinates, otherwise the nearest non-hidden ancestor (city -> region -> country) that
    has coordinates. A hidden node (the "other location" placeholder) is never drawn and
    always resolves up to the real place, so the marker shows its name. None if nothing
    qualifies."""
    if not loc.is_hidden and loc.lat is not None and loc.lng is not None:
        return loc
    return nearest_visible_ancestor_with_coords(loc, by_path, step)


def _build_map_locations(all_locs) -> list:
    """Map markers (issue #113): each location at its own coordinates, or at the nearest
    ancestor with coordinates when it is hidden or has none (see ``map_display_node``).
    Deduplicated so a place isn't drawn twice (its own marker + a resolved child)."""
    by_path = {loc.path: loc for loc in all_locs}
    step = Location.steplen
    data: list = []
    seen: set = set()
    for loc in all_locs:
        display = map_display_node(loc, by_path, step)
        if display is None:
            continue
        key = (str(display.lat), str(display.lng), display.name)
        if key in seen:
            continue
        seen.add(key)
        entry = {
            "id": display.pk,
            "name": display.name,
            "lat": float(display.lat),
            "lng": float(display.lng),
            "is_hidden": display.is_hidden,
        }
        data.append(entry)
    return data


class LocationsMapPage(AsciiSlugMixin, Page):
    intro = RichTextField(blank=True)

    content_panels: ClassVar[list] = [*Page.content_panels, FieldPanel("intro")]

    parent_page_types: ClassVar[list] = ["home.HomePage"]
    subpage_types: ClassVar[list] = []

    override_translatable_fields: ClassVar[list] = [
        SynchronizedField("slug", overridable=False),
    ]

    def get_context(self, request):
        from accounts.models import User

        context = super().get_context(request)
        admin_rank = User.ROLE_HIERARCHY.index(User.Role.ADMIN)
        participant_rank = User.ROLE_HIERARCHY.index(User.Role.PARTICIPANT)
        can_manage = request.user.is_authenticated and (
            request.user.is_superuser or request.user.get_role_rank() >= admin_rank
        )
        all_locs = list(
            Location.objects.filter(is_deleted=False).filter(
                models.Q(proposal__isnull=True) | models.Q(proposal__status=LocationProposal.Status.APPROVED)
            )
        )
        context["locations_data"] = _build_map_locations(all_locs)
        # Only confirmed users (participant+) may propose a location, so only they see the
        # "Add location" button - a guest would otherwise click through to a 403 (issue #118).
        context["can_add"] = request.user.is_authenticated and (
            request.user.is_superuser or request.user.get_role_rank() >= participant_rank
        )
        context["can_manage"] = can_manage
        if can_manage:
            all_locs = Location.objects.filter(is_deleted=False).order_by("name")
            context["all_locations"] = all_locs
        return context

    class Meta:
        verbose_name = "Locations map page"
