from typing import ClassVar

from django.db import models
from treebeard.mp_tree import MP_Node
from wagtail.admin.panels import FieldPanel
from wagtail.fields import RichTextField
from wagtail.models import Page
from wagtail.search import index
from wagtail_localize.fields import SynchronizedField

from cycling_site.page_mixins import AsciiSlugMixin


class Location(MP_Node, index.Indexed):
    name = models.CharField(max_length=255)
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    lng = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    knowledge_article = models.OneToOneField(
        "knowledge.LocationArticlePage",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="location",
    )

    node_order_by: ClassVar[list] = ["name"]

    # name_ru / name_kk / name_en are generated by modeltranslation
    search_fields: ClassVar[list] = [
        index.SearchField("name_ru"),
        index.SearchField("name_kk"),
        index.SearchField("name_en"),
    ]

    panels: ClassVar[list] = [
        FieldPanel("name"),
        FieldPanel("lat"),
        FieldPanel("lng"),
        FieldPanel("knowledge_article"),
    ]

    def __str__(self) -> str:
        return self.name or f"Location #{self.pk}"

    class Meta:
        verbose_name = "Location"
        verbose_name_plural = "Locations"


class LocationsMapPage(AsciiSlugMixin, Page):
    intro = RichTextField(blank=True)

    content_panels: ClassVar[list] = [*Page.content_panels, FieldPanel("intro")]

    parent_page_types: ClassVar[list] = ["home.HomePage"]
    subpage_types: ClassVar[list] = []

    override_translatable_fields: ClassVar[list] = [
        SynchronizedField("slug", overridable=False),
    ]

    def get_context(self, request):
        context = super().get_context(request)
        locations = Location.objects.filter(lat__isnull=False, lng__isnull=False).select_related("knowledge_article")
        loc_data = []
        for loc in locations:
            entry = {
                "name": loc.name,
                "lat": float(loc.lat),
                "lng": float(loc.lng),
            }
            if loc.knowledge_article_id and loc.knowledge_article.live:
                entry["url"] = loc.knowledge_article.url
            loc_data.append(entry)
        context["locations_data"] = loc_data
        return context

    class Meta:
        verbose_name = "Locations map page"
