from typing import ClassVar

from django.db import models
from treebeard.mp_tree import MP_Node
from wagtail.admin.panels import FieldPanel
from wagtail.fields import RichTextField
from wagtail.models import Page
from wagtail.search import index
from wagtail_localize.fields import SynchronizedField

from cycling_site.page_mixins import AsciiSlugMixin


class Location(MP_Node, index.Indexed):
    name = models.CharField(max_length=255)
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    lng = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    knowledge_article = models.OneToOneField(
        "knowledge.LocationArticlePage",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="location",
    )

    is_hidden = models.BooleanField(default=False, db_index=True)
    is_deleted = models.BooleanField(default=False, db_index=True)
    sort_order = models.PositiveSmallIntegerField(default=0, db_index=True)

    node_order_by: ClassVar[list] = ["sort_order", "name"]

    # name_ru / name_kk / name_en are generated by modeltranslation
    search_fields: ClassVar[list] = [
        index.SearchField("name_ru"),
        index.SearchField("name_kk"),
        index.SearchField("name_en"),
        index.FilterField("is_deleted"),
        index.FilterField("is_hidden"),
    ]

    panels: ClassVar[list] = [
        FieldPanel("name"),
        FieldPanel("lat"),
        FieldPanel("lng"),
        FieldPanel("knowledge_article"),
    ]

    def __str__(self) -> str:
        return self.name or f"Location #{self.pk}"

    class Meta:
        verbose_name = "Location"
        verbose_name_plural = "Locations"


class LocationsMapPage(AsciiSlugMixin, Page):
    intro = RichTextField(blank=True)

    content_panels: ClassVar[list] = [*Page.content_panels, FieldPanel("intro")]

    parent_page_types: ClassVar[list] = ["home.HomePage"]
    subpage_types: ClassVar[list] = []

    override_translatable_fields: ClassVar[list] = [
        SynchronizedField("slug", overridable=False),
    ]

    def get_context(self, request):
        from accounts.models import User

        context = super().get_context(request)
        admin_rank = User.ROLE_HIERARCHY.index(User.Role.ADMIN)
        can_manage = request.user.is_authenticated and (
            request.user.is_superuser or request.user.get_role_rank() >= admin_rank
        )
        loc_qs = Location.objects.filter(lat__isnull=False, lng__isnull=False, is_deleted=False)
        if not can_manage:
            loc_qs = loc_qs.filter(is_hidden=False)
        locations = loc_qs.select_related("knowledge_article")
        loc_data = []
        for loc in locations:
            entry = {
                "id": loc.pk,
                "name": loc.name,
                "lat": float(loc.lat),
                "lng": float(loc.lng),
                "is_hidden": loc.is_hidden,
            }
            if loc.knowledge_article_id and loc.knowledge_article.live:
                entry["url"] = loc.knowledge_article.url
            loc_data.append(entry)
        context["locations_data"] = loc_data
        context["can_add"] = can_manage
        context["can_manage"] = can_manage
        if can_manage:
            all_locs = Location.objects.filter(is_deleted=False).order_by("name")
            context["all_locations"] = all_locs
        return context

    class Meta:
        verbose_name = "Locations map page"
