# Generated by Django 6.0.6 on 2026-06-20 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0010_locationproposal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="knowledge_article",
        ),
    ]
